name: Setup Workflow
description: Composite action that sets up bun and installs dependencies
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - run: bun install
      shell: bash
