name: Setup Workflow
description: Composite action that sets up bun and installs dependencies
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version-file: package.json

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: package.json

    - run: bun install
      shell: bash
