name: Setup Workflow
description: Composite action that sets up bun and installs dependencies
runs:
  using: 'composite'
  steps:
    - uses: useblacksmith/setup-node@v5
      with:
        node-version: 22.x

    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Cache dependencies
      uses: useblacksmith/cache@v5

    - run: bun install
      shell: bash
