import { Inter } from "next/font/google";

import { env } from "~/env";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div>Server says {env.SECRET}!</div>
                <main>{props.children}</main>
            </body>
        </html>
    );
}
