import { Inter } from "next/font/google";

import { env } from "~/env";
import { ClientComponent } from "./client-component";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  console.log("Server says", env.SECRET);

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* 👇👇👇 rendering the server secret will cause error because it's tained 👇👇👇 */}
        {/* <div>Server says {env.SECRET}!</div> */}
        <main>{props.children}</main>
      </body>
    </html>
  );
}
